language: csharp
solution: EventGen.sln
mono: none
dotnet: 3.1

script:
  - dotnet build EventGen.sln -c Release
    && dotnet test ./EventGen.Tests.Unit/EventGen.Tests.Unit.csproj -v normal
    && dotnet test ./EventGen.Tests.Integration/EventGen.Tests.Integration.csproj -v normal
    && dotnet test ./EventGen.Tests.Integration.Stress/EventGen.Tests.Integration.Stress.csproj -v normal -c Stress
deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x ./deploy/deploy.sh && ./deploy/deploy.sh $NUGET_API_KEY $NUGET_SOURCE
  on:
    branch: master
matrix:
  fast_finish: true
