language: csharp
solution: DnDGen.EventGen.sln
mono: none
dotnet: 3.1

script:
  - dotnet build DnDGen.EventGen.sln -c Release
    && dotnet test ./DnDGen.EventGen.Tests.Unit/DnDGen.EventGen.Tests.Unit.csproj -v normal
    && dotnet test ./DnDGen.EventGen.Tests.Integration/DnDGen.EventGen.Tests.Integration.csproj -v normal
    && dotnet test ./DnDGen.EventGen.Tests.Integration.Stress/DnDGen.EventGen.Tests.Integration.Stress.csproj -v normal -c Stress
deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x ./deploy/deploy.sh && ./deploy/deploy.sh $NUGET_API_KEY $NUGET_SOURCE
  on:
    branch: master
matrix:
  fast_finish: true
