language: csharp
solution: EventGen.sln
install:
  - nuget restore EventGen.sln
  - nuget install NUnit.Runners -OutputDirectory testrunner
script:
  - xbuild EventGen.sln /p:TargetFrameworkVersion="v4.5" /p:Configuration=Stress
  - set -e
  - mono ./testrunner/NUnit.ConsoleRunner.*/tools/nunit3-console.exe ./EventGen.Tests.Unit/bin/Stress/EventGen.Tests.Unit.dll
  - set -e
  - mono ./testrunner/NUnit.ConsoleRunner.*/tools/nunit3-console.exe ./EventGen.Tests.Integration/bin/Stress/EventGen.Tests.Integration.dll
  - set -e
  - mono ./testrunner/NUnit.ConsoleRunner.*/tools/nunit3-console.exe ./EventGen.Tests.Integration.Stress/bin/Stress/EventGen.Tests.Integration.Stress.dll
deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x ./deploy/deploy.sh && ./deploy/deploy.sh $NUGET_API_KEY $NUGET_SOURCE
  on:
    branch: master
matrix:
  fast_finish: true
